"""
This script processes the output data from a CSV file and converts the tags into a vectorized format. 
It specifically handles the transformation of tags for a music genre classification task, 
where the tags can be 'rap', 'pop', or any other value.
Each tag is converted into a corresponding vector representation, and the resulting vectors are stored in a NumPy array. 
The 'target.npy' file contains the vectorized output data and is generated by this script.
"""
import pandas as pd
import numpy as np

# Print progress of vectorisation each SHOW_PROGRESS iterations
SHOW_PROGRESS = 100

# Load the CSV file with processed output data
output_data = pd.read_csv('processed_output_data.csv')

# Define the vectors for "rap" and "pop"
rap_vector = [0, 1, 0]
pop_vector = [1, 0, 0]
other_vector = [0, 0, 1] 

# Convert each tag to a vector
vectorized_output = []
count=0
for tag in output_data['output']:
    count+=1
    if count%SHOW_PROGRESS==0:
        print(f"{count} output transformed")
    if tag == 'rap':
        vectorized_output.append(rap_vector)
    elif tag == 'pop':
        vectorized_output.append(pop_vector)
    else:
        vectorized_output.append(other_vector)

# Convert the list of lists into a numpy array
vectorized_output = np.array(vectorized_output)

print("---- Vectorisation completed")

# Save the numpy array to a file
np.save('target.npy', vectorized_output)

print("---- Target data saved")

